// Auto-generated by `npx supabase gen types typescript --local`.
// Will be regenerated after each migration in Phase 1.
// Placeholder until first migration lands.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
